import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'nishidy' at '15/09/06 17:59' with Gradle 2.3
 *
 * @author nishidy, @date 15/09/06 17:59
 */
public class ParseWikipediaXMLTest {
    @Test public void testParseWikipediaXML() {

		ArgStore.ifwiki = ""

        ParseWikipediaXML pwxml = new ParseWikipediaXML();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
