/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nishidy' at '15/09/07 21:34' with Gradle 2.3
 *
 * @author nishidy, @date 15/09/07 21:34
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
